const WORKING_TIME = 25;
const LITTLE_BREAK_WORK = 5;
const BIG_BREAK_TIME = 20;
const POMODOROS_IN_ROUND = 4;
const POMODOROS_IN_DAY = 10;

export {
  WORKING_TIME,
  LITTLE_BREAK_WORK,
  BIG_BREAK_TIME,
  POMODOROS_IN_ROUND,
  POMODOROS_IN_DAY,
};
